version: '3'
services:
  ndscheduler:
    image: ndscheduler
    command: ["./node_modules/nodemon/bin/nodemon.js", "-L", "-u", "simple_scheduler/scheduler.py"]
    ports: 
      - "8888:8888"
      - "5861:5861"
    volumes:
      - .:/usr/src/app/ndscheduler
      - ndscheduler_modules:/usr/src/app/ndscheduler/node_modules/
    environment:
      - NDSCHEDULER_SETTINGS_MODULE=simple_scheduler.settings
      - DEBUG=${DEBUG}
    networks:
      - in2it_ndscheduler
  postgres:
    image: postgres:11.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - in2it_ndscheduler
  pgadmin:
    image: dpage/pgadmin4:4.2
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - PGADMIN_LISTEN_PORT=7000
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "7000:7000"
    networks:
      - in2it_ndscheduler
networks:
  in2it_ndscheduler:
    external:
      name: in2it
volumes:
  ndscheduler_modules:
  postgres_data:
  pgadmin_data: